### PR TITLE
fix(set-accessor): css vars in style

### LINKED ISSUE #853: Duplicate class names outputted in pre-render
Stencil 0.8.1.

When using pre-rendering, a component is output with duplicated class names:

screen shot 2018-06-15 at 9 23 14 am

The code in the render that created this:

```javascript
  render() {
    return (
      <div class="site-header container">

        <stencil-route-link url="/" class="logo-link">
          <div class="logo"></div>
          <b class="version">Beta</b>
        </stencil-route-link>
```

### PR DESCRIPTION
**Pull request by manucorporat**
Fixes #853 too

### CODE REVIEW

File: src/renderer/vdom/h.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ const stack: any[] = [];
 
 export function h(nodeName: string | d.FunctionalComponent<d.PropsType>, vnodeData: d.PropsType, child?: d.ChildType): d.VNode;
 export function h(nodeName: string | d.FunctionalComponent<d.PropsType>, vnodeData: d.PropsType, ...children: d.ChildType[]): d.VNode;
-export function h(nodeName: any, vnodeData: any, child?: any) {
```
Comment (manucorporat) [inline src/renderer/vdom/h.ts]: This function, uses arguments, causing a mutation in an arguments causes complete deoptimization, since `arguments` needs to be in sync with all the arguments at any given time.

File: src/renderer/vdom/set-accessor.ts [hunk 2]
```diff
@@ -1,49 +1,39 @@
...
+      const toRemove = oldList.filter(item => !newList.includes(item));
 
-      let classList: string[] = (elm.className == null || elm.className === '') ? EMPTY_ARR : elm.className.trim().split(/\s+/);
+      elm.className = [
+        // delete from classList
+        ...parseClassList(elm.className).filter(item => !toRemove.includes(item)),
 
-      for (i = 0, ilen = oldList.length; i < ilen; i++) {
-        if (newList.indexOf(oldList[i]) === -1) {
-          classList = classList.filter((c: string) => c !== oldList[i]);
```
Comment (manucorporat) [inline src/renderer/vdom/set-accessor.ts]: It's better to call classList once, since it allocates memory.

File: src/renderer/vdom/set-accessor.ts [hunk 3]
```diff
@@ -1,49 +1,39 @@
...
 
   } else if (memberName === 'style') {
-    // Style
-    oldValue = oldValue || EMPTY_OBJ;
-    newValue = newValue || EMPTY_OBJ;
-
-    for (i in oldValue) {
-      if (!newValue[i]) {
-        (elm as any).style[i] = '';
+    for (const prop in oldValue) {
```
Comment (manucorporat) [inline src/renderer/vdom/set-accessor.ts]: Not using i, since the internal type of `i` is a number, not a string. While this is valid JS, it prevents V8 from inlining

File: src/renderer/vdom/set-accessor.ts [hunk 4]
```diff
@@ -1,49 +1,39 @@
...
 
-export function setAccessor(plt: d.PlatformApi, elm: any, memberName: string, oldValue: any, newValue: any, isSvg?: boolean, isHostElement?: boolean, i?: any, ilen?: number, cmpMeta?: d.ComponentMeta) {
+export function setAccessor(plt: d.PlatformApi, elm: HTMLElement, memberName: string, oldValue: any, newValue: any, isSvg: boolean, isHostElement: boolean) {
   if (memberName === 'class' && !isSvg) {
     // Class
     if (oldValue !== newValue) {
-      const oldList: string[] = (oldValue == null || oldValue === '') ? EMPTY_ARR : oldValue.trim().split(/\s+/);
-      const newList: string[] = (newValue == null || newValue === '') ? EMPTY_ARR : newValue.trim().split(/\s+/);
+      const oldList = parseClassList(oldValue);
+      const newList = parseClassList(newValue);
```
Comment (manucorporat) [inline src/renderer/vdom/set-accessor.ts]: Since this code is duplicate 3 times, refactored it out to a function

File: src/renderer/vdom/set-accessor.ts [hunk 5]
```diff
@@ -1,49 +1,39 @@
...
+      const toRemove = oldList.filter(item => !newList.includes(item));
 
-      let classList: string[] = (elm.className == null || elm.className === '') ? EMPTY_ARR : elm.className.trim().split(/\s+/);
+      elm.className = [
```
Comment (manucorporat) [inline src/renderer/vdom/set-accessor.ts]: Final className = currentClassName - toRemove + toAdd

No intermediate allocations!!

File: src/renderer/vdom/set-accessor.ts [hunk 6]
```diff
@@ -112,7 +102,7 @@ export function setAccessor(plt: d.PlatformApi, elm: any, memberName: string, ol
       // also we can ignore the "ref" member name at this point
       setProperty(elm, memberName, newValue == null ? '' : newValue);
       if (newValue == null || newValue === false) {
-        elm.removeAttribute(memberName);
+        plt.domApi.$removeAttribute(elm, memberName);
```
Comment (manucorporat) [inline src/renderer/vdom/set-accessor.ts]: this makes sense, right? probably minifies better
